command_timeout = 5000
add_newline = true
continuation_prompt = "â–¶â–¶"

# ## Most info is on second line
# format = """
# [â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â¯ ](#1c283d)\
# [\uE0B6](#2d333d)$username\
# [\uE0B0](bg:#434C5E fg:#2d333d)$hostname\
# [\uE0B4](fg:#434C5E)
# [â”£â”€](#1c283d)\
# [\uE0B6](#182847)$directory\
# [\uE0B0](fg:#182847 bg:#33658A)$git_branch$git_status\
# [\uE0B0](fg:#33658A bg:#182847)$cmd_duration\
# [\uE0B4](fg:#182847) \
# [\uE0B6](#8A6455)$c$elixir$elm$golang$haskell$java$julia$nodejs$nim$rust$scala$docker_context\
# [\uE0B4](fg:#8A6455)
# [â•°â”€â¯$character](fg:#1c283d)
# """

# # Most info is on first line with empty second line
# format = """
# [â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â¯ ](#1c283d)[\uE0B6](#2d333d)\
# $username[\uE0B0](bg:#434C5E fg:#2d333d)\
# $hostname[\uE0B4](fg:#434C5E) \
# [\uE0B6](#182847)$directory\
# [\uE0B0](fg:#182847 bg:#33658A)$git_branch$git_status\
# [\uE0B0](fg:#33658A bg:#182847)$cmd_duration\
# [\uE0B4](fg:#182847) \
# $fill\
# [\uE0B6](#8A6455)$c$elixir$elm$golang$haskell$java$julia$nodejs$nim$rust$scala$docker_context\
# [\uE0B4](fg:#8A6455)
# [â”£â”€](#1c283d)
# [â•°â”€â¯$character](fg:#1c283d)
# """

# Most info is on first line with empty second line
format = """
[â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â¯ ](#1c283d)[\uE0B6](#2d333d)\
$username[\uE0B0](bg:#434C5E fg:#2d333d)\
$hostname[\uE0B4](fg:#434C5E) \
[\uE0B6](#182847)$directory\
[\uE0B0](fg:#182847 bg:#33658A)$git_branch$git_status\
[\uE0B0](fg:#33658A bg:#182847)$cmd_duration\
[\uE0B4](fg:#182847) \
[\uE0B6](#8A6455)$jobs\
[\uE0B4](fg:#8A6455) \
[\uE0B6](#8A6455)$status\
[\uE0B4](fg:#8A6455)
[â•°â”€â¯$character](fg:#1c283d)
"""

# $fill\
# [\uE0B6](#8A6455)$c$elixir$elm$golang$haskell$java$julia$nodejs$nim$rust$scala$docker_context\

right_format = """[\uE0B6](fg:#182847)$localip[\uE0B4](fg:#182847)"""

[status]
style = 'bg:#8A6455'
# symbol = 'ğŸ”´'
# success_symbol = 'ğŸŸ¢ SUCCESS'
format = '[$common_meaning$pipestatus $status$pipestatus_separator$signal_name$maybe_int]($style)'
map_symbol = true
pipestatus = true
disabled = false

[jobs]
symbol = "+"
number_threshold = 1
symbol_threshold = 1
style = "bg:#8A6455"
format = "[$symbol $number]($style)"

[username]
show_always = true
style_user = "bg:#2d333d"
style_root = "bg:#2d333d"
format = '[$user ]($style)'

[hostname]
ssh_only = false
disabled = false
style = "bg:#434C5E"
format = "[ @ $hostname $ssh_symbol]($style)"
ssh_symbol = "ğŸŒ"

[directory]
style = "bg:#182847"
format = "[ ï»  $read_only $path ]($style)"
truncate_to_repo=false
truncation_length = 4
truncation_symbol = "â€¦/"

[git_branch]
symbol = "ï„“"
style = "bg:#33658A"
format = '[ $symbol  ï˜ $branch ]($style)'

[git_status]
style = "bg:#33658A"
format = '[ $all_status $ahead_behind ]($style)'
conflicted = "="
ahead =	"â‡¡${count}"
behind = "â‡£${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
up_to_date = "ï˜«"
untracked = "?${count}"
stashed = "ï£•"
modified = "!${count}"
staged = "+${count}"
renamed = "Â»${count}"
deleted = "ï™•${count}"
[cmd_duration]
min_time = 1
disabled = false
style = "bg:#182847"
format = '[ took $duration ]($style)'

[localip]
ssh_only = false
style = "bg:#182847"
format = "[ğŸ”—$localipv4]($style)"
disabled = false

[character]
success_symbol = " [ğŸ¼](#ffffff)"
error_symbol = " [âœ—](#e83535)"
vicmd_symbol = " [î˜«](#78b892)"

[fill]
symbol = " "
style = "bold green"

[time]
disabled = false
time_format = "%r" # Hour:Minute Format
style = "bg:#182847"
format = '[ $time ]($style)'

[c]
symbol = "î˜ "
style = "bg:#8A6455"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = "ïŒˆ "
style = "bg:#8A6455"
format = '[ $symbol $context ]($style)$path'

[elixir]
symbol = "î‰µ "
style = "bg:#8A6455"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = "î˜¬ "
style = "bg:#8A6455"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = "î˜§ "
style = "bg:#8A6455"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = "î· "
style = "bg:#8A6455"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = "î‰– "
style = "bg:#8A6455"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = "î˜¤ "
style = "bg:#8A6455"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:#8A6455"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "ïš¤ "
style = "bg:#8A6455"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "î¨"
style = "bg:#8A6455"
format = '[ $symbol ($version) ]($style)'
