# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = true

# A continuation prompt that displays two filled in arrows
continuation_prompt = "â–¶â–¶"

format = """
[â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€> $username $sudo$hostname](bold green)
[â”‚](bold green)$directory $git_branch $git_status $cmd_duration
[â””â”€$character](bold green)"""

right_format = """$localip"""

[line_break]
disabled = false

## First Line of Prompt
[username]
style_user = "bold red"
style_root = "black bold"
format = "[$user]($style)"
disabled = false
show_always = true

[sudo]
style = "bold green"
symbol = "ğŸ—¿"
disabled = false
format = "[as $symbol]($style) "

[hostname]
ssh_only = false
disabled = false
format = "at [$hostname](bold red) [$ssh_symbol](bold blue)"
ssh_symbol = "ğŸŒ"

[localip]
ssh_only = false
format = "ğŸ”—[$localipv4](blue)"
disabled = false

## Second Line of Prompt
[directory]
# format = "[î‚¶](fg:#232526 bg:none)[$path]($style)[î‚´](fg:#232526 bg:#232526)[î‚¶](fg:#6791c9 bg:#232526)[ï»](fg:#232526 bg:#6791c9)[î‚´](fg:#6791c9 bg:none)"
format = "[î‚¶](fg:#232526 bg:none)[$path]($style)[î‚´](fg:#232526 bg:#232526)[î‚¶](fg:#6791c9 bg:#232526)[ï»](fg:#232526 bg:#6791c9)[î‚´](fg:#6791c9 bg:none)[$read_only]($read_only_style) "
style = "fg:#edeff0 bg:#232526"
truncation_length = 3
truncate_to_repo=false
truncation_symbol = "â€¦/"

[cmd_duration]
min_time = 1
format = "[î‚¶](fg:#232526 bg:none)[$duration]($style)[î‚´](fg:#232526 bg:#232526)[î‚¶](fg:#bc83e3 bg:#232526)[ï‰’](fg:#232526 bg:#bc83e3)[î‚´](fg:#bc83e3 bg:none) "
disabled = false
style = "fg:#edeff0 bg:#232526"

## Second Line
[character]
success_symbol = " [ğŸ¼](#6791c9)"
error_symbol = " [îŠ…](#df5b61)"
vicmd_symbol = "[ î˜« ](#78b892)"

## Git on First Line
[git_branch]
format = "[î‚¶](fg:#232526 bg:none)[$branch]($style)[î‚´](fg:#232526 bg:#232526)[î‚¶](fg:#78b892 bg:#232526)[ï˜](fg:#282c34 bg:#78b892)[î‚´](fg:#78b892 bg:none) "
style = "fg:#edeff0 bg:#232526"

[git_status]
format="[î‚¶](fg:#232526 bg:none)[$all_status$ahead_behind]($style)[î‚´](fg:#232526 bg:#232526)[î‚¶](fg:#67afc1 bg:#232526)[îœˆ](fg:#232526 bg:#67afc1)[î‚´](fg:#67afc1 bg:none) "
style = "fg:#edeff0 bg:#232526"
conflicted = "="
ahead =	"â‡¡${count}"
behind = "â‡£${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
up_to_date = "ï˜«"
untracked = "?${count}"
stashed = "ï£•"
modified = "!${count}"
staged = "+${count}"
renamed = "Â»${count}"
deleted = "ï™•${count}"

[git_commit]
format = "[\\($hash\\)]($style) [\\($tag\\)]($style)"
style = "green"

[git_state]
rebase = "REBASING"
merge =	"MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
style =	"yellow"
format = '\([$state( $progress_current/$progress_total)]($style)\) '
